{{
    hist(
        from=ref("test_segment_src"),
        entity_key=["flex_value_id"],
        check_cols=[
            "last_update_date",
        ],
        loaded_at="current_timestamp()",
    )
}}
