version: "1.0"

# Databases
databases:
  - okonomimodell:
      shared: no
      owner: sysadmin
      schemas:
        - stages
        - intermediates
        - marts
        - oebs
        - meta
        - csv

# Roles
roles:
  - okonomimodell_transformer:
      warehouses:
        - okonomimodell_transformer
      privileges:
        databases:
          read:
            - okonomimodell
        schemas:
          read:
            - okonomimodell.stages
            - okonomimodell.csv
            - okonomimodell.intermediates
            - okonomimodell.marts
            - okonomimodell.meta
            - okonomimodell.oebs
          write:
            - okonomimodell.stages
            - okonomimodell.csv
            - okonomimodell.intermediates
            - okonomimodell.marts
            - okonomimodell.meta
            - okonomimodell.oebs
        tables:
          read:
            - okonomimodell.stages.*
            - okonomimodell.csv.*
            - okonomimodell.intermediates.*
            - okonomimodell.marts.*
            - okonomimodell.meta.*
            - okonomimodell.oebs.*
          write:
            - okonomimodell.stages.*
            - okonomimodell.csv.*
            - okonomimodell.intermediates.*
            - okonomimodell.marts.*
            - okonomimodell.meta.*
            - okonomimodell.oebs.*
      owns:
        tables:
          - okonomimodell.stages.*
          - okonomimodell.csv.*
          - okonomimodell.intermediates.*
          - okonomimodell.marts.*
          - okonomimodell.meta.*
          - okonomimodell.oebs.*
      owner: useradmin

  - okonomimodell_reporter:
      privileges:
        databases:
          read:
            - okonomimodell
        schemas:
          read:
            - okonomimodell.marts
            - okonomimodell.meta
        tables:
          read:
            - okonomimodell.marts.*
            - okonomimodell.meta.*
      owner: useradmin

warehouses:
  - okonomimodell_transformer:
      size: x-small
      owner: sysadmin


