databases:
  - name: okonomimodell
    transient: false
    data_retention_time_in_days: 1
    schemas:
      - name: stages
      - name: intermediates
      - name: marts
      - name: oebs
      - name: meta
      - name: csv
      
warehouses:
  - name: okonomimodell_transformer

users:
  - name: srv_okonomimodell_runner
    type: legacy_service
      
roles:
  - name: okonomimodell_transformer
  - name: okonomimodell_reporter
      
grants:
  - role: okonomimodell_transformer   
    warehouses:
        - okonomimodell_transformer
    write_on_schemas:
        - okonomimodell.stages
        - okonomimodell.csv
        - okonomimodell.intermediates
        - okonomimodell.marts
        - okonomimodell.meta
        - okonomimodell.oebs
    to_users:
        - srv_okonomimodell_runner
    to_roles:
        - airflow_orchestrator
  - role: okonomimodell_reporter
    read_on_schemas:
            - okonomimodell.marts
            - okonomimodell.meta
    to_roles:
        - eiendom_transformer
        - faktura_transformer
        - innkjop_transformer
        - regnskap_transformer
        - reporting_airflow
        - reporting_transformer





