id: okonomimodell

databases:
  - name: okonomimodell
    transient: false
    data_retention_time_in_days: 1
    schemas:
      - name: stages
      - name: intermediates
      - name: marts
      - name: meta
      - name: csv

  - name: okonomimodell_raw
    transient: false
    data_retention_time_in_days: 30
    schemas:
      - name: oebs
      - name: snapshots

warehouses:
  - name: okonomimodell_transformer

roles:
  - name: okonomimodell_transformer
  - name: okonomimodell_reporter

grants:
  - role: okonomimodell_transformer
    warehouses:
        - okonomimodell_transformer
    write_on_schemas:
        - okonomimodell.stages
        - okonomimodell.csv
        - okonomimodell.intermediates
        - okonomimodell.marts
        - okonomimodell.meta
        - okonomimodell_raw.snapshots
    read_on_schemas:
        - okonomimodell_raw.oebs
    to_roles:
        - airflow_orchestrator
  - role: okonomimodell_reporter
    read_on_schemas:
            - okonomimodell.marts
            - okonomimodell.meta
    to_roles:
        - eiendom_transformer
        - faktura_transformer
        - innkjop_transformer
        - regnskap_transformer
        - reporting_airflow
        - reporting_transformer
